openapi: 3.0.0
info:
  title: API Documentation Test
  version: 1.0.0
  description: '<h1><u>Html Text Rendered </u></h1>'
paths:
  /test:
    get:
      summary: Sample endpoint
      responses:
        '200':
          description: '<h1><u>Html Text Rendered </u></h1>'
